# Generated by Django 4.0.6 on 2022-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=50, verbose_name='Name of Product')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('descriptionPoint', models.TextField(verbose_name='description')),
            ],
        ),
    ]
