# Generated by Django 4.0.6 on 2022-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand_name',
            field=models.CharField(default='null', max_length=50, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='products',
            name='theme',
            field=models.CharField(default='null', max_length=100, verbose_name='Theme Name'),
        ),
    ]
