# Generated by Django 4.0.6 on 2022-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_brand_name_products_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_url1',
            field=models.URLField(default='null', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_url2',
            field=models.URLField(default='null', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_url3',
            field=models.URLField(default='null', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_url4',
            field=models.URLField(default='null', verbose_name='Image 4'),
        ),
    ]
