# Generated by Django 4.0.6 on 2022-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('amount', models.FloatField(verbose_name='Total Amount')),
                ('city', models.CharField(max_length=100, verbose_name='Customer Address')),
                ('state', models.CharField(max_length=100, verbose_name='Customer Address')),
                ('country', models.CharField(max_length=100, verbose_name='Customer Address')),
                ('status', models.CharField(max_length=100, verbose_name='Payment Status')),
            ],
        ),
    ]
