# Generated by Django 4.0.6 on 2022-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_version', models.DateField()),
                ('created', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=20, verbose_name='currency')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('customer', models.CharField(max_length=20, verbose_name='customer')),
                ('payment_method', models.CharField(max_length=20, verbose_name='payment method id')),
            ],
        ),
    ]
