# Generated by Django 4.0.6 on 2022-07-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='country',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_method',
        ),
    ]
